#################################################################
#  _____ _      _                    _                 _        #
# |  __ (_)    | |                  | |               (_)       #
# | |__) |  ___| |_ _   _ _ __ ___  | |     ___   __ _ _ _ __   #
# |  ___/ |/ __| __| | | | '__/ _ \ | |    / _ \ / _` | | '_ \  #
# | |   | | (__| |_| |_| | | |  __/ | |___| (_) | (_| | | | | | #
# |_|   |_|\___|\__|\__,_|_|  \___| |______\___/ \__, |_|_| |_| #
#                                                 __/ |         #
#                                                |___/          #
#################################################################

#############
# 语言设置
########
# 可用语言: en_US, zh_CN
# 语言文件位于插件的lang文件夹中
# 您也可以创建自己的语言文件

language: "en_us"

#############
# 消息设置
########
# 每一行代表一条消息，留空为空行
# (如果图像高度为8，您最多可以设置8行消息)
# 支持聊天颜色代码
########
# 可用变量:
# %pname%       - 玩家名称 (无格式)
# %online%      - 在线玩家数
# %max%         - 最大玩家数
# %motd%        - 服务器MOTD
# %displayname% - 玩家显示名称
########
# 注意: 如果安装了PlaceholderAPI插件
#       您也可以使用其提供的所有变量

messages:
    - ''
    - '&7欢迎来到 &e&l我的服务器&7!'
    - ''
    - '&7» 当前在线: [&e%online%&7/&e%max%&7] 玩家'
    - '&7» &a最新公告: &7已添加新功能!'
    - ''
    - '&7» &aPictureLogin &7插件 &a作者Lythrilla&NathanG&7'
    - ''

#############
# 首次加入消息
########
# 设置为true可在玩家首次加入时
# 显示不同的消息
# 可使用上述相同的变量

show-first-join: true

first-join-messages:
    - ''
    - '&7欢迎来到 &e&l我的服务器&7!'
    - ''
    - '&7» 当前在线: [&e%online%&7/&e%max%&7] 玩家'
    - '&7» &a最新公告: &7已添加新功能!'
    - ''
    - '&7请大家欢迎 &a%pname% &7加入服务器!'
    - ''

#############
# 离开消息
########
# 设置为true可在玩家
# 离开服务器时显示消息
# 可使用上述相同的变量

show-leave-message: false

leave-messages:
    - ''
    - '&e%pname% &7离开了服务器!'
    - ''
    - '&7» 当前在线: [&e%online%&7/&e%max%&7] 玩家'
    - '&7» &a最新公告: &7已添加新功能!'
    - ''
    - '&7» &aPictureLogin &7插件 &a作者Lythrilla&NathanG&7'
    - ''

#############
# 备用图片
########
# 如果启用，插件无法加载玩家头像时
# 将使用备用图片
# 备用图片位置:
# > plugins/PictureLogin/fallback.png

fallback: true

#############
# 清空聊天
########
# 设置为true可在发送消息前
# 清空聊天记录
# 可选值: [true|false]

clear-chat: false

#############
# 文本居中
########
# 是否将图片旁边的文本居中显示
# 可选值: [true|false]

center-text: false

#############
# 屏蔽默认加入/离开消息
########
# 设置为true可屏蔽
# 默认的加入和离开消息

block-join-message: false
block-leave-message: false

#############
# 仅对玩家显示
########
# 设置为true只向
# 加入的玩家发送登录消息

player-only: true

#############
# 图像字符
######## 
# 更改此项可修改图像的构成字符
########
# 可选值:
# - BLOCK (方块)
# - DARK_SHADE (深色阴影)
# - MEDIUM_SHADE (中等阴影)
# - LIGHT_SHADE (浅色阴影)

character: 'BLOCK'

#############
# 图像URL
######## 
# 获取玩家头像的URL
# 默认使用minepic
# 建议保持默认设置
########
# 可用变量:
# %uuid%   - 玩家UUID
# %pname%  - 玩家用户名

url: 'https://minepic.org/avatar/8/%uuid%'

# 离线服务器请使用此URL:
# url: 'https://minepic.org/avatar/8/%pname%'

#############
# 异步处理
########
# 设置为true可在异步线程上生成图像
# 这将减少性能影响，但可能会延迟消息显示

async: true

#############
# 权限要求
########
# 设置为false将向所有登录的玩家
# 显示消息，无论他们是否拥有
# picturelogin.show权限

require-permission: true

#############
# 插件挂钩
########
# 设置为false可禁止PictureLogin
# 与特定插件进行集成

hooks:
  PlaceholderAPI: true
  AuthMe: true

#############
# 更新检查
########
# 如果启用，插件将在服务器启动时
# 检查更新，并在控制台中
# 发送一条消息(如果找到更新)

update-check: true

#############
# 统计数据
########
# 允许此插件向bStats发送匿名统计数据?
# https://bstats.org/
# 设置为false可禁用

metrics: true