#################################################################
#  _____ _      _                    _                 _        #
# |  __ (_)    | |                  | |               (_)       #
# | |__) |  ___| |_ _   _ _ __ ___  | |     ___   __ _ _ _ __   #
# |  ___/ |/ __| __| | | | '__/ _ \ | |    / _ \ / _` | | '_ \  #
# | |   | | (__| |_| |_| | | |  __/ | |___| (_) | (_| | | | | | #
# |_|   |_|\___|\__|\__,_|_|  \___| |______\___/ \__, |_|_| |_| #
#                                                 __/ |         #
#                                                |___/          #
#################################################################

#############
# 语言设置
########
# 可用语言: en_US, zh_CN
# 语言文件位于插件的lang文件夹中
# 您也可以创建自己的语言文件

language: "en_us"

#############
# 消息设置
########
# 每一行代表一条消息，留空为空行
# (如果图像高度为8，您最多可以设置8行消息)
# 支持聊天颜色代码(&)和MiniMessage格式(<bold>, <gradient>, 等)
########
# 可用变量:
# %pname%       - 玩家名称 (无格式)
# %online%      - 在线玩家数
# %max%         - 最大玩家数
# %motd%        - 服务器MOTD
# %displayname% - 玩家显示名称
########
# 注意: 如果安装了PlaceholderAPI插件
#       您也可以使用其提供的所有变量
########
# MiniMessage示例:
# - '<rainbow>欢迎光临我的服务器</rainbow>'
# - '<gradient:red:blue>这是渐变文字</gradient>'
# - '<yellow>黄色文字 <bold>加粗文字</bold></yellow>'

messages:
    - ''
    - '<gray>欢迎来到 <yellow><bold>我的服务器</bold></yellow><gray>!'
    - '<rainbow>★ VIP玩家专属效果 ★</rainbow>'
    - '<gray>» 当前在线: [<yellow>%online%</yellow><gray>/<yellow>%max%</yellow><gray>] 玩家'
    - '<gray>» <green>最新公告: </green><gray>已添加新功能!'
    - ''
    - '<gradient:green:blue>» PictureLogin 插件 作者Lythrilla&NathanG</gradient>'
    - ''

#############
# 首次加入消息
########
# 设置为true可在玩家首次加入时
# 显示不同的消息
# 可使用上述相同的变量

show-first-join: true

first-join-messages:
    - ''
    - '<gray>欢迎来到 <yellow><bold>我的服务器</bold></yellow><gray>!'
    - ''
    - '<gray>» 当前在线: [<yellow>%online%</yellow><gray>/<yellow>%max%</yellow><gray>] 玩家'
    - '<gray>» <green>最新公告: </green><gray>已添加新功能!'
    - ''
    - '<gray>请大家欢迎 <green>%pname% </green><gray>加入服务器!'
    - ''

#############
# 离开消息
########
# 设置为true可在玩家
# 离开服务器时显示消息
# 可使用上述相同的变量

show-leave-message: false

leave-messages:
    - ''
    - '<yellow>%pname% </yellow><gray>离开了服务器!'
    - ''
    - '<gray>» 当前在线: [<yellow>%online%</yellow><gray>/<yellow>%max%</yellow><gray>] 玩家'
    - '<gray>» <green>最新公告: </green><gray>已添加新功能!'
    - ''
    - '<gray>» <green>PictureLogin </green><gray>插件 <green>作者Lythrilla&NathanG</green><gray>'
    - ''

#############
# 备用图片
########
# 如果启用，插件无法加载玩家头像时
# 将使用备用图片
# 备用图片位置:
# > plugins/PictureLogin/fallback.png

fallback: true

#############
# 清空聊天
########
# 设置为true可在发送消息前
# 清空聊天记录
# 可选值: [true|false]

clear-chat: false

#############
# 文本居中
########
# 是否将图片旁边的文本居中显示
# 可选值: [true|false]

center-text: false

#############
# 屏蔽默认加入/离开消息
########
# 设置为true可屏蔽
# 默认的加入和离开消息

block-join-message: false
block-leave-message: false

#############
# 登录音效
########
# 设置为true可在玩家登录时
# 播放音效

play-login-sound: true

# 登录音效设置
login-sound:
  # 音效名称 (Minecraft原版音效名)
  # 完整列表: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
  sound: "ENTITY_PLAYER_LEVELUP"
  # 音量 (0.0 - 1.0)
  volume: 1.0
  # 音调 (0.5 - 2.0)
  pitch: 1.0

#############
# 仅对玩家显示
########
# 设置为true只向
# 加入的玩家发送登录消息

player-only: true

#############
# 图像字符
######## 
# 更改此项可修改图像的构成字符
########
# 可选值:
# - BLOCK (方块)
# - DARK_SHADE (深色阴影)
# - MEDIUM_SHADE (中等阴影)
# - LIGHT_SHADE (浅色阴影)

character: 'BLOCK'

#############
# 图像URL
######## 
# 获取玩家头像的URL
# 默认使用minepic
# 插件会根据服务器模式自动处理URL:
# - 正版服务器: 使用玩家UUID
# - 离线服务器: 自动使用玩家名称
########
# 可用变量:
# %uuid%   - 玩家UUID
# %pname%  - 玩家用户名

url: 'https://minepic.org/avatar/8/%uuid%'

# 注意: 如果您的服务器是离线模式，但URL中只有%uuid%变量，
# 插件会自动将%uuid%替换为玩家名称

# 如果您使用SkinsRestorer插件，且玩家有自定义皮肤，
# 插件会自动使用该皮肤的数据获取头像

#############
# 异步处理
########
# 设置为true可在异步线程上生成图像
# 这将减少性能影响，但可能会延迟消息显示

async: true

#############
# 权限要求
########
# 设置为false将向所有登录的玩家
# 显示消息，无论他们是否拥有
# picturelogin.show权限

require-permission: true

#############
# 插件挂钩
########
# 设置为false可禁止PictureLogin
# 与特定插件进行集成

hooks:
  PlaceholderAPI: true
  AuthMe: true
  SkinsRestorer: true

#############
# 更新检查
########
# 如果启用，插件将在服务器启动时
# 检查更新，并在控制台中
# 发送一条消息(如果找到更新)

update-check: true

#############
# 统计数据
########
# 允许此插件向bStats发送匿名统计数据?
# https://bstats.org/
# 设置为false可禁用

metrics: true

#############
# 自定义消息系统
########
# 以下设置允许您为特定玩家或权限组设置自定义消息
# 启用后，插件将检查users.yml和perms.yml中的配置

# 启用基于玩家的自定义消息 (users.yml)
enable-user-messages: true

# 启用基于权限的自定义消息 (perms.yml)
enable-permission-messages: true

#############
# 命令设置
########
# 以下设置允许您启用或禁用
# 特定命令功能

settings:
  enable_commands:
    reload: true
    language:
      language: true
      set: true
    debug: true

# 消息优先级顺序 (从高到低):
# 1. 玩家特定消息 (users.yml)
# 2. 权限组消息 (perms.yml，按优先级排序)
# 3. 默认消息 (此配置文件)