name: PictureLogin
version: '${version}'
main: me.Lythrilla.picturelogin.PictureLogin
authors: [Lythrilla, NathanG]
api-version: '1.16'
softdepend: [PlaceholderAPI, AuthMe, SkinsRestorer, PremiumVanish]

commands:
  picturelogin:
    description: PictureLogin插件主命令
    usage: /picturelogin <reload|version|language|help|debug>
    aliases: [piclogin, plogin, pl]
    permission: picturelogin.use

permissions:
  picturelogin.use:
    description: 允许使用PictureLogin命令
    default: true
  
  picturelogin.show:
    description: 允许玩家看到登录消息
    default: true
  
  picturelogin.reload:
    description: 允许重载PictureLogin插件配置
    default: op
    
  picturelogin.language:
    description: 允许更改插件语言
    default: op
    
  picturelogin.debug:
    description: 允许使用调试命令
    default: op
    
  picturelogin.group.vip:
    description: VIP玩家的自定义消息权限
    default: false
    
  picturelogin.group.admin:
    description: 管理员的自定义消息权限
    default: op
    
  picturelogin.effect.rainbow:
    description: 彩虹特效权限
    default: false
    
  picturelogin.effect.gradient:
    description: 渐变特效权限
    default: false
