name: 构建PictureLogin插件

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  # 允许手动触发工作流
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin' # Eclipse Temurin JDK
        
    - name: 验证Gradle Wrapper
      uses: gradle/wrapper-validation-action@v2
      
    - name: 设置Gradle
      uses: gradle/actions/setup-gradle@v3
        
    - name: 使用Gradle构建
      run: gradle build
      
    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: PictureLogin
        path: build/libs/PictureLogin-*.jar
        retention-days: 14

  # 添加版本发布工作流
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: 验证Gradle Wrapper
      uses: gradle/wrapper-validation-action@v2
      
    - name: 设置Gradle
      uses: gradle/actions/setup-gradle@v3
        
    - name: 使用Gradle构建
      run: gradle shadowJar
      
    - name: 创建GitHub发布
      uses: softprops/action-gh-release@v2
      with:
        files: build/libs/PictureLogin-*.jar
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 